### ISSUE TITLE
fix: have a go session form validation

### ISSUE THREAD

**Issue by chrisvfabio** [ChagasCo/enw-angular#33]
Add name attribute to form element and rename attribute (without alpha-numeric characters)

**Comment by andreachagas** [comment]
I changed the names to the ng-message to exclude the underscore.

**Comment by andreachagas** [comment]
Reopened as I closed it accidentally before testing it

**Comment by chrisvfabio** [comment]
issue resolved. Closing issue. 

Refer to Pull Request: #58
